#!/bin/bash

# ––– everything in color –––––––––––––––––––––––––––––––––––––––––––––––––––––
#   Make files' content available textually, nicely colored for viewing.
#   Used as input preprocessor for `less` in `eview`.
#   Uses `etext`, but provides highlighting and covers additional types.
# –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––


# usage message
if [ $# -eq 0 ]
then
  echo
  echo "Usage: ecolor NAME"
  echo
  echo "Prints a textual representation of contents in color."
  echo "Based on \`etext\`, but goes beyond regular files."
  echo
  exit 1
fi

# log
exec {logfd}> >(logger -t ecolor)
function log {
  echo "$*" >&$logfd
}

# red output
function echo_red {
  echo -e "\e[1;31m$*\e[0m"
}

# bat call
bat_cmd=$(type -P bat batcat | head -n1)
if [[ -z "$bat_cmd" ]]
then
  echo "bat / batcat not found" >&2
  exit 1
fi
bat() {
  LESSOPEN="" "$bat_cmd" \
    --color=always \
    --paging=never \
    --style=plain \
    --wrap=never \
    "$@"
}


# main code –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

# pathname
pn=$(realpath --no-symlinks "$1")
# `--no-symlinks` → use extension of symlink, not target
log "file: $pn"

# non-existing
if [[ ! -e "$pn" ]]
then
  log "type: (symlink to) non-existing"
  if [[ -L "$pn" ]]
  then
    echo_red "Broken symlink."
  else
    echo_red "No such entry."
  fi
  exit 0
fi

# directory
if [[ -d "$pn" ]]
then
  log "type: directory"
  # use `eza`
  eza --color=always $EZA_OPTIONS "$pn"
  exit 0
fi

# special files: named pipe (fifo), socket, block device, character device
if [[ -p "$pn" || -S "$pn" || -b "$pn" || -c "$pn" ]]
then
  log "type: special"
  # use `stat`
  stat "$pn" | tail -n +2 | bat --language meminfo
  # meminfo highlighting gives best results for stat output
  exit 0
fi

# empty
if [[ ! -s "$pn" ]]
then
  # nothing to read, "empty"
  log "type: empty"
  echo_red "Empty."
  exit 0
fi

# process with `etext`
opn="$pn"
pn=$(etext "$pn" --filename)
log "showing $pn"

# determine whether (processed) input is binary
encoding=$(file --dereference --mime-encoding --brief "$pn")
if [[ "$encoding" == "binary" ]]
then
  # binary
  log "type: binary"
  echo -n "binary: "
  file --dereference --brief "$pn"
  hexyl "$pn"
  exit 0
fi

# text
log "type: text"
# if requested by `esearch`, highlight pattern-matching lines
if [[ -n "$ESEARCH_PATTERN" ]]
then
  # use rg because `pn` has aready been preprocessed
  bat_highlight=$(
    rg \
      $ESEARCH_OPTIONS \
      --line-number \
      -- \
      "$ESEARCH_PATTERN" \
      "$pn" \
    | sed 's/^\([0-9]*\):.*/-H \1/'
  )
else
  bat_highlight=""
fi
bat $bat_highlight "$pn"

# display original if possible
columns=${COLUMNS:-$(tput cols 2>/dev/null || echo 80)}
lines=${LINES:-$(tput lines 2>/dev/null || echo 24)}
chafa \
  --format symbols \
  --view-size $(( columns * 80 / 100 ))x$(( lines * 80 / 100 )) \
  --animate off \
  --polite=on \
  "$opn" \
  2> /dev/null
