#!/bin/bash

# ––– search everything –––––––––––––––––––––––––––––––––––––––––––––––––––––––
#   Search files' content with ripgrep using `etext` as preprocessor,
#   and browse the result interactively with `fzf` with `ecolor` preview
#   and `eview` full view.
# –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––


# usage message
if [[ $# -eq 1 && ( "$1" == "-h" || "$1" == "--help" ) ]]
then
  echo
  echo "Usage: esearch [RG-OPTIONS] [PATTERN]"
  echo
  echo "Searches for pattern in files recursively from current directory."
  echo
  echo "If no pattern is specified, all files are listed without grepping."
  echo "The last argument is interpreted as PATTERN, unless it starts"
  echo "with '--', except if the preceding option is '--'."
  echo
  echo "To get a list of possible RG-OPTIONS, use `rg -h` or `man rg`."
  echo "Options including spaces are not supported."
  echo "Multiple patters and pattern files are not supported."
  echo "Use `esearch -h` or `esearch --help` for this message."
  echo
  exit 1
fi

# process arguments
if [[ $# -eq 0 ]]; then
  ESEARCH_PATTERN=""
  ESEARCH_OPTIONS=""
else
  last="${@: -1}"
  second_last="${@: -2:1}"
  if [[ "$last" == --* && "$second_last" != "--" ]]; then
    ESEARCH_PATTERN=""
    ESEARCH_OPTIONS="$*"
  else
    ESEARCH_PATTERN="$last"
    ESEARCH_OPTIONS="${*:1:$#-1}"
  fi
fi
# for functions below called in child shells as well as for `ecolor`
export ESEARCH_PATTERN
export ESEARCH_OPTIONS

# for `fzf --preview`
function ESEARCH_PREVIEW {
  if [[ -n "$ESEARCH_PATTERN" ]]
  then
    # show search results in preview
    rg \
      $ESEARCH_OPTIONS \
      --pre etext \
      --color=always \
      --line-number \
      --field-match-separator=":" \
      --trim \
      -- \
      "$ESEARCH_PATTERN" \
      "$1"
  else
    # show file in preview
    ecolor "$1"
  fi
}
export -f ESEARCH_PREVIEW

# for `fzf --bind`
function ESEARCH_VIEW {
  if [[ -n "$ESEARCH_PATTERN" ]]
  then
    # call eview (less) with options
    # - specifying search pattern does not search, and search wraps around
    # - specify search pattern
    # - show column with search markers
    # - show line numbers
    # - do not clear / restore screen
    eview \
      --search-options=KW \
      "+/$ESEARCH_PATTERN" \
      --status-column \
      --LINE-NUMBERS \
      --no-init \
      "$@"
  else
    eview "$@"
  fi
}
export -f ESEARCH_VIEW

# call rg
function rg_ {
  if [[ -n "$ESEARCH_PATTERN" ]]
  then
    # list files matching pattern
    rg \
      --no-ignore-vcs \
      $ESEARCH_OPTIONS \
      --line-buffered \
      --pre etext \
      --files-with-matches \
      -- \
      "$ESEARCH_PATTERN"
  else
    # list all files
    rg \
      --no-ignore-vcs \
      $ESEARCH_OPTIONS \
      --line-buffered \
      --files
  fi
}

# colorize rg file list
cdir=$(tput setaf 39)
cfile=$(tput setaf 214)
creset=$(tput sgr0)
function colorize {
  sed --unbuffered -E 's|^(.*\/)?([^/]*)$|'$cdir'\1'$cfile'\2'$creset'|'
}

# call fzf
bind_focus='focus:transform-header(file --brief --mime {})'
bind_focus+='+transform-preview-label:(echo " $(basename {}) ")'
function fzf_ {
  fzf \
    --exact \
    --scheme=path \
    --reverse \
    --style full \
    --header-label ' File Type ' \
    --bind "$bind_focus" \
    --preview "ESEARCH_PREVIEW {}" \
    --multi \
    --delimiter=/ \
    --ansi \
    --bind 'enter:execute(ESEARCH_VIEW {+})' \
    --preview-window=noinfo,wrap-word \
    --color=label:bold:214
}


# main code –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

# stop pipe when quitting fzf
# also needs unbuffered / reduced buffer in rg_ and colorize
set -o pipefail

# run search and display
export ETEXT_ERR=$(mktemp)
rg_ | colorize | fzf_
# display error messages
cat $ETEXT_ERR

# prune cache, suppressing message
etext > /dev/null

# override fzf exit status
exit 0
