#!/bin/bash

# ––– view everything –––––––––––––––––––––––––––––––––––––––––––––––––––––––
#   Wrapper for `less` with `ecolor` as preprocessor.
#   Used by `esearch`.
# –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––


# TODO: usage if no arguments

# usage message
if [[ $# -eq 1 && ( "$1" == "-h" || "$1" == "--help" ) ]]
then
  echo
  echo "Usage: eview NAMES"
  echo
  echo "Shows a textual representation of contents in color, within \`less\`."
  echo "Based on \`ecolor\`."
  echo "If no arguments are given, the current directory is listed."
  echo
  exit 1
fi

# no arguments: directory listing
if [ $# -eq 0 ]
then
  ecolor .
  exit 0
fi

# environment variables for `less`
# `ecolor` as preprocessor
export LESSOPEN='|| ecolor %s'
unset LESSCLOSE
# necessary?
export COLUMNS
# for opening files ("editing")
export LESSEDIT="xdg-open %g"
# quit on ESC ESC; Ctrl+Left and Right to switch documents
export LESSKEY_CONTENT="#command
\e[1\;5D prev-file
\e[1\;5C next-file
"
# setting LESSKEY_CONTENT induces strange screen clearing behavior
# setting also LESS_LINES ameliorates that, at the price of slower scrolling
export LESS_LINES=${LINES:-$(tput lines 2>/dev/null)}

# call `less` with options
# - pass through and account for escape sequences
# - show long prompt by default
# - enable colored text in prompts etc.
# - set (long) prompt to orange bold + standout = reverse
# - search result, no special colors but standout
# - line number color, standard "light black"
# - define prompt
#   M                       define long prompt
#   ?m█🭪 %i ◢◤ %m 🭨█:.     # / #, if there is more than one input file, 
#   ?f█🭪 %f 🭨█:.          file name, if it is known
#   █🭪 %lt?L ◢◤ %L:. 🭨█"   line number at top, / last line number if known
# - put found search result in line 4
# - make search case-insensitive
# - search wraps around
# - wrap by words
less \
  --RAW-CONTROL-CHARS \
  --LONG-PROMPT \
  --use-color \
  --color=P214ds \
  --color=S-.-s \
  --color=N8.0 \
  --prompt='M?m█🭪 %i ◢◤ %m 🭨█:.?f█🭪 %f 🭨█:.█🭪 %lt?L ◢◤ %L:. 🭨█' \
  --jump-target=4 \
  --ignore-case \
  --search-options=W \
  --wordwrap \
  "$@"

# prune cache, suppressing message
etext > /dev/null
