#!/bin/bash


# ––– search everything –––––––––––––––––––––––––––––––––––––––––––––––––––––––
# Search files' content with ripgrep using `eview` as preprocessor.
# –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––


rg --pre eread "$@"

# TODO: --pre-glob, extracted from `eread`
# TODO: clean cache
# TODO: set and show EREAD_ERR